default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: djo
  password: cicibu

development:
  <<: *default
  database: BlogAppRails_development
  host: localhost
  username: djo
  password: cicibu

test:
  <<: *default
  database: BlogAppRails_test
  host: localhost
  username: djo
  password: cicibu

production:
  <<: *default
  database: BlogAppRails_production
  username: BlogAppRails
  password: <%= ENV["BLOGAPPRAILS_DATABASE_PASSWORD"] %>
